name: smart_park_app

description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  shared_preferences: any
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  smooth_page_indicator: ^1.2.1



  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

