name: smart
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  shared_preferences: any
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.12
  scoped_model: ^2.0.0
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  latlong2: ^0.9.0
  flutter_map: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/bottom-nav-bar/
    - assets/images/home/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
